// <auto-generated />
using System;
using BeeApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeeApp.Infrastructure.Migrations
{
    [DbContext(typeof(BeeAppDbContext))]
    partial class BeeAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeeApp.Domain.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BeeBread")
                        .HasColumnType("bit");

                    b.Property<bool>("BeeBrood")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eggs")
                        .HasColumnType("bit");

                    b.Property<bool>("Feed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QueenBee")
                        .HasColumnType("bit");

                    b.Property<bool>("QueenCell")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("BeeApp.Domain.Entities.Inspection", b =>
                {
                    b.OwnsOne("BeeApp.Domain.Entities.BeehiveDetails", "BeehiveDetails", b1 =>
                        {
                            b1.Property<int>("InspectionId")
                                .HasColumnType("int");

                            b1.Property<string>("BeehiveType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("LastInspection")
                                .HasColumnType("datetime2");

                            b1.Property<string>("QueenType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InspectionId");

                            b1.ToTable("Inspections");

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.Navigation("BeehiveDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
